version: '3.7'
services:
  slackbot:
    container_name: 'slackbot'
    build: './slackbot'
    ports:
      - '8080:8080'
    volumes:
      - './slackbot:/go/src/app'
    environment:
      SLACK_ACCESS_KEY: ${SLACK_ACCESS_KEY:?err}
      WIT_AI_ACCESS_KEY: ${WIT_AI_ACCESS_KEY:?err}
      WOLFRAM_APP_ID: ${WOLFRAM_APP_ID:?err}
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'