version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/soulchips/go-slackbot
    steps:
      
      - checkout
      - run: go get github.com/pilu/fresh
      - run: go get github.com/Krognol/go-wolfram
      - run: go get github.com/christianrondeau/go-wit
      - run: go get github.com/joho/godotenv
      - run: go get github.com/nlopes/slack
      - run: go get go.mongodb.org/mongo-driver/mongo
      - run: go get go.mongodb.org/mongo-driver/mongo/options
      - run: ls
      - run: go test -v ./...